# Generated by Django 5.0.2 on 2024-04-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0005_category_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo1', models.ImageField(blank=True, null=True, upload_to='dimg')),
                ('logo2', models.ImageField(blank=True, null=True, upload_to='dimg')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('phoneMobile', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=10)),
                ('facebookUrl', models.URLField(max_length=255)),
                ('twitterUrl', models.URLField(max_length=255)),
                ('instagramUrl', models.URLField(max_length=255)),
                ('youtubeUrl', models.URLField(max_length=255)),
            ],
        ),
    ]
